name: Copy Apple secrets to better-bear

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy secrets
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          CERT: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          CERT_PW: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
          PW: ${{ secrets.APPLE_ID_PASSWORD }}
          TEAM: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          echo "$CERT" | gh secret set APPLE_CERTIFICATE_BASE64 -R mreider/better-bear
          echo "$CERT_PW" | gh secret set APPLE_CERTIFICATE_PASSWORD -R mreider/better-bear
          echo "$EMAIL" | gh secret set APPLE_ID_EMAIL -R mreider/better-bear
          echo "$PW" | gh secret set APPLE_ID_PASSWORD -R mreider/better-bear
          echo "$TEAM" | gh secret set APPLE_TEAM_ID -R mreider/better-bear
          echo "Done"

